default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres # from postgres container
  password: <%= ENV['DEV_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: finale_development

test:
  <<: *default
  database: finale_test

# TODO
production:
  <<: *default
  database: finale_production
  username: finale
  password: <%= ENV['FINALE_DATABASE_PASSWORD'] %>
